package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DmClientMdmNtnltyCntryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDmClientMdmNtnltyCntryAllPropertiesEquals(DmClientMdmNtnltyCntry expected, DmClientMdmNtnltyCntry actual) {
        assertDmClientMdmNtnltyCntryAutoGeneratedPropertiesEquals(expected, actual);
        assertDmClientMdmNtnltyCntryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDmClientMdmNtnltyCntryAllUpdatablePropertiesEquals(
        DmClientMdmNtnltyCntry expected,
        DmClientMdmNtnltyCntry actual
    ) {
        assertDmClientMdmNtnltyCntryUpdatableFieldsEquals(expected, actual);
        assertDmClientMdmNtnltyCntryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDmClientMdmNtnltyCntryAutoGeneratedPropertiesEquals(
        DmClientMdmNtnltyCntry expected,
        DmClientMdmNtnltyCntry actual
    ) {
        assertThat(expected)
            .as("Verify DmClientMdmNtnltyCntry auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDmClientMdmNtnltyCntryUpdatableFieldsEquals(DmClientMdmNtnltyCntry expected, DmClientMdmNtnltyCntry actual) {
        assertThat(expected)
            .as("Verify DmClientMdmNtnltyCntry relevant properties")
            .satisfies(e -> assertThat(e.getPrtyFk()).as("check prtyFk").isEqualTo(actual.getPrtyFk()))
            .satisfies(e -> assertThat(e.getFrstNtnltFrmt()).as("check frstNtnltFrmt").isEqualTo(actual.getFrstNtnltFrmt()))
            .satisfies(e -> assertThat(e.getFrstContinent()).as("check frstContinent").isEqualTo(actual.getFrstContinent()))
            .satisfies(e -> assertThat(e.getScndNtnltFrmt()).as("check scndNtnltFrmt").isEqualTo(actual.getScndNtnltFrmt()))
            .satisfies(e -> assertThat(e.getScndContinent()).as("check scndContinent").isEqualTo(actual.getScndContinent()))
            .satisfies(e -> assertThat(e.getThrdNtnltFrmt()).as("check thrdNtnltFrmt").isEqualTo(actual.getThrdNtnltFrmt()))
            .satisfies(e -> assertThat(e.getThrdContinent()).as("check thrdContinent").isEqualTo(actual.getThrdContinent()))
            .satisfies(e -> assertThat(e.getFrthNtnltFrmt()).as("check frthNtnltFrmt").isEqualTo(actual.getFrthNtnltFrmt()))
            .satisfies(e -> assertThat(e.getFrthContinent()).as("check frthContinent").isEqualTo(actual.getFrthContinent()))
            .satisfies(e -> assertThat(e.getTechLineage()).as("check techLineage").isEqualTo(actual.getTechLineage()))
            .satisfies(e -> assertThat(e.getTechCreatedDate()).as("check techCreatedDate").isEqualTo(actual.getTechCreatedDate()))
            .satisfies(e -> assertThat(e.getTechUpdatedDate()).as("check techUpdatedDate").isEqualTo(actual.getTechUpdatedDate()))
            .satisfies(e -> assertThat(e.getTechMapping()).as("check techMapping").isEqualTo(actual.getTechMapping()))
            .satisfies(e -> assertThat(e.getTechComment()).as("check techComment").isEqualTo(actual.getTechComment()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDmClientMdmNtnltyCntryUpdatableRelationshipsEquals(
        DmClientMdmNtnltyCntry expected,
        DmClientMdmNtnltyCntry actual
    ) {}
}
