package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DmOResvAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDmOResvAllPropertiesEquals(DmOResv expected, DmOResv actual) {
        assertDmOResvAutoGeneratedPropertiesEquals(expected, actual);
        assertDmOResvAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDmOResvAllUpdatablePropertiesEquals(DmOResv expected, DmOResv actual) {
        assertDmOResvUpdatableFieldsEquals(expected, actual);
        assertDmOResvUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDmOResvAutoGeneratedPropertiesEquals(DmOResv expected, DmOResv actual) {
        assertThat(expected)
            .as("Verify DmOResv auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDmOResvUpdatableFieldsEquals(DmOResv expected, DmOResv actual) {
        assertThat(expected)
            .as("Verify DmOResv relevant properties")
            .satisfies(e -> assertThat(e.getNumLigne1()).as("check numLigne1").isEqualTo(actual.getNumLigne1()))
            .satisfies(e -> assertThat(e.getResort2()).as("check resort2").isEqualTo(actual.getResort2()))
            .satisfies(e -> assertThat(e.getResvNameId3()).as("check resvNameId3").isEqualTo(actual.getResvNameId3()))
            .satisfies(e -> assertThat(e.getClientOId4()).as("check clientOId4").isEqualTo(actual.getClientOId4()))
            .satisfies(e -> assertThat(e.getTypeChb5()).as("check typeChb5").isEqualTo(actual.getTypeChb5()))
            .satisfies(e -> assertThat(e.getConfirmationNo6()).as("check confirmationNo6").isEqualTo(actual.getConfirmationNo6()))
            .satisfies(e -> assertThat(e.getClientMdmId7()).as("check clientMdmId7").isEqualTo(actual.getClientMdmId7()))
            .satisfies(e -> assertThat(e.getNameId8()).as("check nameId8").isEqualTo(actual.getNameId8()))
            .satisfies(e -> assertThat(e.getParentResvNameId9()).as("check parentResvNameId9").isEqualTo(actual.getParentResvNameId9()))
            .satisfies(e -> assertThat(e.getContactId10()).as("check contactId10").isEqualTo(actual.getContactId10()))
            .satisfies(e -> assertThat(e.getAgenceId11()).as("check agenceId11").isEqualTo(actual.getAgenceId11()))
            .satisfies(e -> assertThat(e.getAgenceNom12()).as("check agenceNom12").isEqualTo(actual.getAgenceNom12()))
            .satisfies(e -> assertThat(e.getSocieteId13()).as("check societeId13").isEqualTo(actual.getSocieteId13()))
            .satisfies(e -> assertThat(e.getGroupeId14()).as("check groupeId14").isEqualTo(actual.getGroupeId14()))
            .satisfies(e -> assertThat(e.getNumBloc15()).as("check numBloc15").isEqualTo(actual.getNumBloc15()))
            .satisfies(e -> assertThat(e.getTypeResv16()).as("check typeResv16").isEqualTo(actual.getTypeResv16()))
            .satisfies(e -> assertThat(e.getStatutResv17()).as("check statutResv17").isEqualTo(actual.getStatutResv17()))
            .satisfies(e -> assertThat(e.getDateDebutResv18()).as("check dateDebutResv18").isEqualTo(actual.getDateDebutResv18()))
            .satisfies(e -> assertThat(e.getDateFinResv19()).as("check dateFinResv19").isEqualTo(actual.getDateFinResv19()))
            .satisfies(
                e -> assertThat(e.getTruncDateDebutResv20()).as("check truncDateDebutResv20").isEqualTo(actual.getTruncDateDebutResv20())
            )
            .satisfies(e -> assertThat(e.getTruncDateFinResv21()).as("check truncDateFinResv21").isEqualTo(actual.getTruncDateFinResv21()))
            .satisfies(e -> assertThat(e.getDateAnnResv22()).as("check dateAnnResv22").isEqualTo(actual.getDateAnnResv22()))
            .satisfies(e -> assertThat(e.getPseudoRoomYn23()).as("check pseudoRoomYn23").isEqualTo(actual.getPseudoRoomYn23()))
            .satisfies(e -> assertThat(e.getCreateurResv24()).as("check createurResv24").isEqualTo(actual.getCreateurResv24()))
            .satisfies(e -> assertThat(e.getNomCreateurResv25()).as("check nomCreateurResv25").isEqualTo(actual.getNomCreateurResv25()))
            .satisfies(e -> assertThat(e.getCodeGarantie26()).as("check codeGarantie26").isEqualTo(actual.getCodeGarantie26()))
            .satisfies(e -> assertThat(e.getFlgDed27()).as("check flgDed27").isEqualTo(actual.getFlgDed27()))
            .satisfies(e -> assertThat(e.getCodePays28()).as("check codePays28").isEqualTo(actual.getCodePays28()))
            .satisfies(e -> assertThat(e.getLibPays29()).as("check libPays29").isEqualTo(actual.getLibPays29()))
            .satisfies(e -> assertThat(e.getCodeNationalite30()).as("check codeNationalite30").isEqualTo(actual.getCodeNationalite30()))
            .satisfies(e -> assertThat(e.getLibNationalite31()).as("check libNationalite31").isEqualTo(actual.getLibNationalite31()))
            .satisfies(e -> assertThat(e.getCodeSource32()).as("check codeSource32").isEqualTo(actual.getCodeSource32()))
            .satisfies(e -> assertThat(e.getLibSource33()).as("check libSource33").isEqualTo(actual.getLibSource33()))
            .satisfies(e -> assertThat(e.getCodeGrandSource34()).as("check codeGrandSource34").isEqualTo(actual.getCodeGrandSource34()))
            .satisfies(e -> assertThat(e.getCodeOrigine35()).as("check codeOrigine35").isEqualTo(actual.getCodeOrigine35()))
            .satisfies(e -> assertThat(e.getLibOrigine36()).as("check libOrigine36").isEqualTo(actual.getLibOrigine36()))
            .satisfies(e -> assertThat(e.getCodeMarche37()).as("check codeMarche37").isEqualTo(actual.getCodeMarche37()))
            .satisfies(e -> assertThat(e.getLibMarche38()).as("check libMarche38").isEqualTo(actual.getLibMarche38()))
            .satisfies(e -> assertThat(e.getCodeGrandMarche39()).as("check codeGrandMarche39").isEqualTo(actual.getCodeGrandMarche39()))
            .satisfies(e -> assertThat(e.getLibGrandMarche40()).as("check libGrandMarche40").isEqualTo(actual.getLibGrandMarche40()))
            .satisfies(e -> assertThat(e.getCodePrix41()).as("check codePrix41").isEqualTo(actual.getCodePrix41()))
            .satisfies(e -> assertThat(e.getCategPrix42()).as("check categPrix42").isEqualTo(actual.getCategPrix42()))
            .satisfies(e -> assertThat(e.getLibPrix43()).as("check libPrix43").isEqualTo(actual.getLibPrix43()))
            .satisfies(e -> assertThat(e.getNumChb44()).as("check numChb44").isEqualTo(actual.getNumChb44()))
            .satisfies(
                e -> assertThat(e.getDescriptionTypeChb45()).as("check descriptionTypeChb45").isEqualTo(actual.getDescriptionTypeChb45())
            )
            .satisfies(e -> assertThat(e.getCodeTypeChb46()).as("check codeTypeChb46").isEqualTo(actual.getCodeTypeChb46()))
            .satisfies(e -> assertThat(e.getClassChb47()).as("check classChb47").isEqualTo(actual.getClassChb47()))
            .satisfies(e -> assertThat(e.getCaractChb48()).as("check caractChb48").isEqualTo(actual.getCaractChb48()))
            .satisfies(
                e ->
                    assertThat(e.getTypeChbDeReservation49())
                        .as("check typeChbDeReservation49")
                        .isEqualTo(actual.getTypeChbDeReservation49())
            )
            .satisfies(
                e ->
                    assertThat(e.getDescriptionTypeChbDeResv50())
                        .as("check descriptionTypeChbDeResv50")
                        .isEqualTo(actual.getDescriptionTypeChbDeResv50())
            )
            .satisfies(
                e -> assertThat(e.getCodeTypeChbDeResv51()).as("check codeTypeChbDeResv51").isEqualTo(actual.getCodeTypeChbDeResv51())
            )
            .satisfies(
                e -> assertThat(e.getStatutDeReservation52()).as("check statutDeReservation52").isEqualTo(actual.getStatutDeReservation52())
            )
            .satisfies(
                e -> assertThat(e.getCircuitDistribution53()).as("check circuitDistribution53").isEqualTo(actual.getCircuitDistribution53())
            )
            .satisfies(
                e ->
                    assertThat(e.getCircuitDistribUserRegroup54())
                        .as("check circuitDistribUserRegroup54")
                        .isEqualTo(actual.getCircuitDistribUserRegroup54())
            )
            .satisfies(e -> assertThat(e.getNumCrs55()).as("check numCrs55").isEqualTo(actual.getNumCrs55()))
            .satisfies(e -> assertThat(e.getTypeRefCrs56()).as("check typeRefCrs56").isEqualTo(actual.getTypeRefCrs56()))
            .satisfies(e -> assertThat(e.getCrsInsertDate57()).as("check crsInsertDate57").isEqualTo(actual.getCrsInsertDate57()))
            .satisfies(e -> assertThat(e.getDateCreaResv58()).as("check dateCreaResv58").isEqualTo(actual.getDateCreaResv58()))
            .satisfies(e -> assertThat(e.getDatePremier59()).as("check datePremier59").isEqualTo(actual.getDatePremier59()))
            .satisfies(e -> assertThat(e.getStatutPremier60()).as("check statutPremier60").isEqualTo(actual.getStatutPremier60()))
            .satisfies(e -> assertThat(e.getDateDernier61()).as("check dateDernier61").isEqualTo(actual.getDateDernier61()))
            .satisfies(e -> assertThat(e.getStatutDernier62()).as("check statutDernier62").isEqualTo(actual.getStatutDernier62()))
            .satisfies(
                e -> assertThat(e.getDateDernierPseudo63()).as("check dateDernierPseudo63").isEqualTo(actual.getDateDernierPseudo63())
            )
            .satisfies(
                e -> assertThat(e.getStatutDernierPseudo64()).as("check statutDernierPseudo64").isEqualTo(actual.getStatutDernierPseudo64())
            )
            .satisfies(e -> assertThat(e.getDiffDtCreaAnn65()).as("check diffDtCreaAnn65").isEqualTo(actual.getDiffDtCreaAnn65()))
            .satisfies(e -> assertThat(e.getDiffDtArrAnn66()).as("check diffDtArrAnn66").isEqualTo(actual.getDiffDtArrAnn66()))
            .satisfies(e -> assertThat(e.getLeadtime67()).as("check leadtime67").isEqualTo(actual.getLeadtime67()))
            .satisfies(e -> assertThat(e.getLos68()).as("check los68").isEqualTo(actual.getLos68()))
            .satisfies(e -> assertThat(e.getOccupantsGroupe69()).as("check occupantsGroupe69").isEqualTo(actual.getOccupantsGroupe69()))
            .satisfies(e -> assertThat(e.getNbNuitee70()).as("check nbNuitee70").isEqualTo(actual.getNbNuitee70()))
            .satisfies(e -> assertThat(e.getNbNuiteeNnDed71()).as("check nbNuiteeNnDed71").isEqualTo(actual.getNbNuiteeNnDed71()))
            .satisfies(e -> assertThat(e.getNbResvAnn72()).as("check nbResvAnn72").isEqualTo(actual.getNbResvAnn72()))
            .satisfies(e -> assertThat(e.getNbAdu73()).as("check nbAdu73").isEqualTo(actual.getNbAdu73()))
            .satisfies(e -> assertThat(e.getNbEnf74()).as("check nbEnf74").isEqualTo(actual.getNbEnf74()))
            .satisfies(e -> assertThat(e.getNbPersDayU75()).as("check nbPersDayU75").isEqualTo(actual.getNbPersDayU75()))
            .satisfies(e -> assertThat(e.getNbPersArr76()).as("check nbPersArr76").isEqualTo(actual.getNbPersArr76()))
            .satisfies(e -> assertThat(e.getNbPersDep77()).as("check nbPersDep77").isEqualTo(actual.getNbPersDep77()))
            .satisfies(e -> assertThat(e.getNbPersAnn78()).as("check nbPersAnn78").isEqualTo(actual.getNbPersAnn78()))
            .satisfies(e -> assertThat(e.getNbPersNoshow79()).as("check nbPersNoshow79").isEqualTo(actual.getNbPersNoshow79()))
            .satisfies(e -> assertThat(e.getNbChbDayU80()).as("check nbChbDayU80").isEqualTo(actual.getNbChbDayU80()))
            .satisfies(e -> assertThat(e.getNbChbArr81()).as("check nbChbArr81").isEqualTo(actual.getNbChbArr81()))
            .satisfies(e -> assertThat(e.getNbChbDep82()).as("check nbChbDep82").isEqualTo(actual.getNbChbDep82()))
            .satisfies(e -> assertThat(e.getNbChbAnn83()).as("check nbChbAnn83").isEqualTo(actual.getNbChbAnn83()))
            .satisfies(e -> assertThat(e.getNbChbNoshow84()).as("check nbChbNoshow84").isEqualTo(actual.getNbChbNoshow84()))
            .satisfies(e -> assertThat(e.getRevenuNetChambre85()).as("check revenuNetChambre85").isEqualTo(actual.getRevenuNetChambre85()))
            .satisfies(
                e -> assertThat(e.getRevenuTaxeChambre86()).as("check revenuTaxeChambre86").isEqualTo(actual.getRevenuTaxeChambre86())
            )
            .satisfies(
                e ->
                    assertThat(e.getRevenuNetChambreGlobal87())
                        .as("check revenuNetChambreGlobal87")
                        .isEqualTo(actual.getRevenuNetChambreGlobal87())
            )
            .satisfies(
                e ->
                    assertThat(e.getRevenuTaxeChambreGlobal88())
                        .as("check revenuTaxeChambreGlobal88")
                        .isEqualTo(actual.getRevenuTaxeChambreGlobal88())
            )
            .satisfies(e -> assertThat(e.getRevenuNetBq89()).as("check revenuNetBq89").isEqualTo(actual.getRevenuNetBq89()))
            .satisfies(e -> assertThat(e.getRevenuTaxeBq90()).as("check revenuTaxeBq90").isEqualTo(actual.getRevenuTaxeBq90()))
            .satisfies(
                e -> assertThat(e.getRevenuNetBqGlobal91()).as("check revenuNetBqGlobal91").isEqualTo(actual.getRevenuNetBqGlobal91())
            )
            .satisfies(
                e -> assertThat(e.getRevenuTaxeBqGlobal92()).as("check revenuTaxeBqGlobal92").isEqualTo(actual.getRevenuTaxeBqGlobal92())
            )
            .satisfies(e -> assertThat(e.getRevenuNetExtra93()).as("check revenuNetExtra93").isEqualTo(actual.getRevenuNetExtra93()))
            .satisfies(e -> assertThat(e.getRevenuTaxeExtra94()).as("check revenuTaxeExtra94").isEqualTo(actual.getRevenuTaxeExtra94()))
            .satisfies(
                e ->
                    assertThat(e.getRevenuNetExtraGlobal95())
                        .as("check revenuNetExtraGlobal95")
                        .isEqualTo(actual.getRevenuNetExtraGlobal95())
            )
            .satisfies(
                e ->
                    assertThat(e.getRevenuTaxeExtraGlobal96())
                        .as("check revenuTaxeExtraGlobal96")
                        .isEqualTo(actual.getRevenuTaxeExtraGlobal96())
            )
            .satisfies(e -> assertThat(e.getRevenuNetTotal97()).as("check revenuNetTotal97").isEqualTo(actual.getRevenuNetTotal97()))
            .satisfies(e -> assertThat(e.getRevenuTaxeTotal98()).as("check revenuTaxeTotal98").isEqualTo(actual.getRevenuTaxeTotal98()))
            .satisfies(
                e ->
                    assertThat(e.getRevenuNetTotalGlobal99())
                        .as("check revenuNetTotalGlobal99")
                        .isEqualTo(actual.getRevenuNetTotalGlobal99())
            )
            .satisfies(
                e ->
                    assertThat(e.getRevenuTaxeTotalGlobal100())
                        .as("check revenuTaxeTotalGlobal100")
                        .isEqualTo(actual.getRevenuTaxeTotalGlobal100())
            )
            .satisfies(
                e -> assertThat(e.getProdRevenuChambre101()).as("check prodRevenuChambre101").isEqualTo(actual.getProdRevenuChambre101())
            )
            .satisfies(e -> assertThat(e.getProdRevenuBq102()).as("check prodRevenuBq102").isEqualTo(actual.getProdRevenuBq102()))
            .satisfies(e -> assertThat(e.getProdRevenuExtra103()).as("check prodRevenuExtra103").isEqualTo(actual.getProdRevenuExtra103()))
            .satisfies(e -> assertThat(e.getProdRevenuTotal104()).as("check prodRevenuTotal104").isEqualTo(actual.getProdRevenuTotal104()))
            .satisfies(
                e ->
                    assertThat(e.getProdChambreNbNuitees105())
                        .as("check prodChambreNbNuitees105")
                        .isEqualTo(actual.getProdChambreNbNuitees105())
            )
            .satisfies(e -> assertThat(e.getTechCreateDate106()).as("check techCreateDate106").isEqualTo(actual.getTechCreateDate106()))
            .satisfies(e -> assertThat(e.getTechUpdateDate107()).as("check techUpdateDate107").isEqualTo(actual.getTechUpdateDate107()))
            .satisfies(e -> assertThat(e.getNumLigne108()).as("check numLigne108").isEqualTo(actual.getNumLigne108()))
            .satisfies(e -> assertThat(e.getResort109()).as("check resort109").isEqualTo(actual.getResort109()))
            .satisfies(e -> assertThat(e.getResvNameId110()).as("check resvNameId110").isEqualTo(actual.getResvNameId110()))
            .satisfies(e -> assertThat(e.getClientOId111()).as("check clientOId111").isEqualTo(actual.getClientOId111()))
            .satisfies(e -> assertThat(e.getTypeChb112()).as("check typeChb112").isEqualTo(actual.getTypeChb112()))
            .satisfies(e -> assertThat(e.getConfirmationNo113()).as("check confirmationNo113").isEqualTo(actual.getConfirmationNo113()))
            .satisfies(e -> assertThat(e.getClientMdmId114()).as("check clientMdmId114").isEqualTo(actual.getClientMdmId114()))
            .satisfies(e -> assertThat(e.getNameId115()).as("check nameId115").isEqualTo(actual.getNameId115()))
            .satisfies(
                e -> assertThat(e.getParentResvNameId116()).as("check parentResvNameId116").isEqualTo(actual.getParentResvNameId116())
            )
            .satisfies(e -> assertThat(e.getContactId117()).as("check contactId117").isEqualTo(actual.getContactId117()))
            .satisfies(e -> assertThat(e.getAgenceId118()).as("check agenceId118").isEqualTo(actual.getAgenceId118()))
            .satisfies(e -> assertThat(e.getAgenceNom119()).as("check agenceNom119").isEqualTo(actual.getAgenceNom119()))
            .satisfies(e -> assertThat(e.getSocieteId120()).as("check societeId120").isEqualTo(actual.getSocieteId120()))
            .satisfies(e -> assertThat(e.getGroupeId121()).as("check groupeId121").isEqualTo(actual.getGroupeId121()))
            .satisfies(e -> assertThat(e.getNumBloc122()).as("check numBloc122").isEqualTo(actual.getNumBloc122()))
            .satisfies(e -> assertThat(e.getTypeResv123()).as("check typeResv123").isEqualTo(actual.getTypeResv123()))
            .satisfies(e -> assertThat(e.getStatutResv124()).as("check statutResv124").isEqualTo(actual.getStatutResv124()))
            .satisfies(e -> assertThat(e.getDateDebutResv125()).as("check dateDebutResv125").isEqualTo(actual.getDateDebutResv125()))
            .satisfies(e -> assertThat(e.getDateFinResv126()).as("check dateFinResv126").isEqualTo(actual.getDateFinResv126()))
            .satisfies(
                e -> assertThat(e.getTruncDateDebutResv127()).as("check truncDateDebutResv127").isEqualTo(actual.getTruncDateDebutResv127())
            )
            .satisfies(
                e -> assertThat(e.getTruncDateFinResv128()).as("check truncDateFinResv128").isEqualTo(actual.getTruncDateFinResv128())
            )
            .satisfies(e -> assertThat(e.getDateAnnResv129()).as("check dateAnnResv129").isEqualTo(actual.getDateAnnResv129()))
            .satisfies(e -> assertThat(e.getPseudoRoomYn130()).as("check pseudoRoomYn130").isEqualTo(actual.getPseudoRoomYn130()))
            .satisfies(e -> assertThat(e.getCreateurResv131()).as("check createurResv131").isEqualTo(actual.getCreateurResv131()))
            .satisfies(e -> assertThat(e.getNomCreateurResv132()).as("check nomCreateurResv132").isEqualTo(actual.getNomCreateurResv132()))
            .satisfies(e -> assertThat(e.getCodeGarantie133()).as("check codeGarantie133").isEqualTo(actual.getCodeGarantie133()))
            .satisfies(e -> assertThat(e.getFlgDed134()).as("check flgDed134").isEqualTo(actual.getFlgDed134()))
            .satisfies(e -> assertThat(e.getCodePays135()).as("check codePays135").isEqualTo(actual.getCodePays135()))
            .satisfies(e -> assertThat(e.getLibPays136()).as("check libPays136").isEqualTo(actual.getLibPays136()))
            .satisfies(e -> assertThat(e.getCodeNationalite137()).as("check codeNationalite137").isEqualTo(actual.getCodeNationalite137()))
            .satisfies(e -> assertThat(e.getLibNationalite138()).as("check libNationalite138").isEqualTo(actual.getLibNationalite138()))
            .satisfies(e -> assertThat(e.getCodeSource139()).as("check codeSource139").isEqualTo(actual.getCodeSource139()))
            .satisfies(e -> assertThat(e.getLibSource140()).as("check libSource140").isEqualTo(actual.getLibSource140()))
            .satisfies(e -> assertThat(e.getCodeGrandSource141()).as("check codeGrandSource141").isEqualTo(actual.getCodeGrandSource141()))
            .satisfies(e -> assertThat(e.getCodeOrigine142()).as("check codeOrigine142").isEqualTo(actual.getCodeOrigine142()))
            .satisfies(e -> assertThat(e.getLibOrigine143()).as("check libOrigine143").isEqualTo(actual.getLibOrigine143()))
            .satisfies(e -> assertThat(e.getCodeMarche144()).as("check codeMarche144").isEqualTo(actual.getCodeMarche144()))
            .satisfies(e -> assertThat(e.getLibMarche145()).as("check libMarche145").isEqualTo(actual.getLibMarche145()))
            .satisfies(e -> assertThat(e.getCodeGrandMarche146()).as("check codeGrandMarche146").isEqualTo(actual.getCodeGrandMarche146()))
            .satisfies(e -> assertThat(e.getLibGrandMarche147()).as("check libGrandMarche147").isEqualTo(actual.getLibGrandMarche147()))
            .satisfies(e -> assertThat(e.getCodePrix148()).as("check codePrix148").isEqualTo(actual.getCodePrix148()))
            .satisfies(e -> assertThat(e.getCategPrix149()).as("check categPrix149").isEqualTo(actual.getCategPrix149()))
            .satisfies(e -> assertThat(e.getLibPrix150()).as("check libPrix150").isEqualTo(actual.getLibPrix150()))
            .satisfies(e -> assertThat(e.getNumChb151()).as("check numChb151").isEqualTo(actual.getNumChb151()))
            .satisfies(
                e -> assertThat(e.getDescriptionTypeChb152()).as("check descriptionTypeChb152").isEqualTo(actual.getDescriptionTypeChb152())
            )
            .satisfies(e -> assertThat(e.getCodeTypeChb153()).as("check codeTypeChb153").isEqualTo(actual.getCodeTypeChb153()))
            .satisfies(e -> assertThat(e.getClassChb154()).as("check classChb154").isEqualTo(actual.getClassChb154()))
            .satisfies(e -> assertThat(e.getCaractChb155()).as("check caractChb155").isEqualTo(actual.getCaractChb155()))
            .satisfies(
                e ->
                    assertThat(e.getTypeChbDeReservation156())
                        .as("check typeChbDeReservation156")
                        .isEqualTo(actual.getTypeChbDeReservation156())
            )
            .satisfies(
                e ->
                    assertThat(e.getDescriptionTypeChbDeResv157())
                        .as("check descriptionTypeChbDeResv157")
                        .isEqualTo(actual.getDescriptionTypeChbDeResv157())
            )
            .satisfies(
                e -> assertThat(e.getCodeTypeChbDeResv158()).as("check codeTypeChbDeResv158").isEqualTo(actual.getCodeTypeChbDeResv158())
            )
            .satisfies(
                e ->
                    assertThat(e.getStatutDeReservation159())
                        .as("check statutDeReservation159")
                        .isEqualTo(actual.getStatutDeReservation159())
            )
            .satisfies(
                e ->
                    assertThat(e.getCircuitDistribution160())
                        .as("check circuitDistribution160")
                        .isEqualTo(actual.getCircuitDistribution160())
            )
            .satisfies(
                e ->
                    assertThat(e.getCircuitDistribUserRegroup161())
                        .as("check circuitDistribUserRegroup161")
                        .isEqualTo(actual.getCircuitDistribUserRegroup161())
            )
            .satisfies(e -> assertThat(e.getNumCrs162()).as("check numCrs162").isEqualTo(actual.getNumCrs162()))
            .satisfies(e -> assertThat(e.getTypeRefCrs163()).as("check typeRefCrs163").isEqualTo(actual.getTypeRefCrs163()))
            .satisfies(e -> assertThat(e.getCrsInsertDate164()).as("check crsInsertDate164").isEqualTo(actual.getCrsInsertDate164()))
            .satisfies(e -> assertThat(e.getDateCreaResv165()).as("check dateCreaResv165").isEqualTo(actual.getDateCreaResv165()))
            .satisfies(e -> assertThat(e.getDatePremier166()).as("check datePremier166").isEqualTo(actual.getDatePremier166()))
            .satisfies(e -> assertThat(e.getStatutPremier167()).as("check statutPremier167").isEqualTo(actual.getStatutPremier167()))
            .satisfies(e -> assertThat(e.getDateDernier168()).as("check dateDernier168").isEqualTo(actual.getDateDernier168()))
            .satisfies(e -> assertThat(e.getStatutDernier169()).as("check statutDernier169").isEqualTo(actual.getStatutDernier169()))
            .satisfies(
                e -> assertThat(e.getDateDernierPseudo170()).as("check dateDernierPseudo170").isEqualTo(actual.getDateDernierPseudo170())
            )
            .satisfies(
                e ->
                    assertThat(e.getStatutDernierPseudo171())
                        .as("check statutDernierPseudo171")
                        .isEqualTo(actual.getStatutDernierPseudo171())
            )
            .satisfies(e -> assertThat(e.getDiffDtCreaAnn172()).as("check diffDtCreaAnn172").isEqualTo(actual.getDiffDtCreaAnn172()))
            .satisfies(e -> assertThat(e.getDiffDtArrAnn173()).as("check diffDtArrAnn173").isEqualTo(actual.getDiffDtArrAnn173()))
            .satisfies(e -> assertThat(e.getLeadtime174()).as("check leadtime174").isEqualTo(actual.getLeadtime174()))
            .satisfies(e -> assertThat(e.getLos175()).as("check los175").isEqualTo(actual.getLos175()))
            .satisfies(e -> assertThat(e.getOccupantsGroupe176()).as("check occupantsGroupe176").isEqualTo(actual.getOccupantsGroupe176()))
            .satisfies(e -> assertThat(e.getNbNuitee177()).as("check nbNuitee177").isEqualTo(actual.getNbNuitee177()))
            .satisfies(e -> assertThat(e.getNbNuiteeNnDed178()).as("check nbNuiteeNnDed178").isEqualTo(actual.getNbNuiteeNnDed178()))
            .satisfies(e -> assertThat(e.getNbResvAnn179()).as("check nbResvAnn179").isEqualTo(actual.getNbResvAnn179()))
            .satisfies(e -> assertThat(e.getNbAdu180()).as("check nbAdu180").isEqualTo(actual.getNbAdu180()))
            .satisfies(e -> assertThat(e.getNbEnf181()).as("check nbEnf181").isEqualTo(actual.getNbEnf181()))
            .satisfies(e -> assertThat(e.getNbPersDayU182()).as("check nbPersDayU182").isEqualTo(actual.getNbPersDayU182()))
            .satisfies(e -> assertThat(e.getNbPersArr183()).as("check nbPersArr183").isEqualTo(actual.getNbPersArr183()))
            .satisfies(e -> assertThat(e.getNbPersDep184()).as("check nbPersDep184").isEqualTo(actual.getNbPersDep184()))
            .satisfies(e -> assertThat(e.getNbPersAnn185()).as("check nbPersAnn185").isEqualTo(actual.getNbPersAnn185()))
            .satisfies(e -> assertThat(e.getNbPersNoshow186()).as("check nbPersNoshow186").isEqualTo(actual.getNbPersNoshow186()))
            .satisfies(e -> assertThat(e.getNbChbDayU187()).as("check nbChbDayU187").isEqualTo(actual.getNbChbDayU187()))
            .satisfies(e -> assertThat(e.getNbChbArr188()).as("check nbChbArr188").isEqualTo(actual.getNbChbArr188()))
            .satisfies(e -> assertThat(e.getNbChbDep189()).as("check nbChbDep189").isEqualTo(actual.getNbChbDep189()))
            .satisfies(e -> assertThat(e.getNbChbAnn190()).as("check nbChbAnn190").isEqualTo(actual.getNbChbAnn190()))
            .satisfies(e -> assertThat(e.getNbChbNoshow191()).as("check nbChbNoshow191").isEqualTo(actual.getNbChbNoshow191()))
            .satisfies(
                e -> assertThat(e.getRevenuNetChambre192()).as("check revenuNetChambre192").isEqualTo(actual.getRevenuNetChambre192())
            )
            .satisfies(
                e -> assertThat(e.getRevenuTaxeChambre193()).as("check revenuTaxeChambre193").isEqualTo(actual.getRevenuTaxeChambre193())
            )
            .satisfies(
                e ->
                    assertThat(e.getRevenuNetChambreGlobal194())
                        .as("check revenuNetChambreGlobal194")
                        .isEqualTo(actual.getRevenuNetChambreGlobal194())
            )
            .satisfies(
                e ->
                    assertThat(e.getRevenuTaxeChambreGlobal195())
                        .as("check revenuTaxeChambreGlobal195")
                        .isEqualTo(actual.getRevenuTaxeChambreGlobal195())
            )
            .satisfies(e -> assertThat(e.getRevenuNetBq196()).as("check revenuNetBq196").isEqualTo(actual.getRevenuNetBq196()))
            .satisfies(e -> assertThat(e.getRevenuTaxeBq197()).as("check revenuTaxeBq197").isEqualTo(actual.getRevenuTaxeBq197()))
            .satisfies(
                e -> assertThat(e.getRevenuNetBqGlobal198()).as("check revenuNetBqGlobal198").isEqualTo(actual.getRevenuNetBqGlobal198())
            )
            .satisfies(
                e -> assertThat(e.getRevenuTaxeBqGlobal199()).as("check revenuTaxeBqGlobal199").isEqualTo(actual.getRevenuTaxeBqGlobal199())
            )
            .satisfies(e -> assertThat(e.getRevenuNetExtra200()).as("check revenuNetExtra200").isEqualTo(actual.getRevenuNetExtra200()))
            .satisfies(e -> assertThat(e.getRevenuTaxeExtra201()).as("check revenuTaxeExtra201").isEqualTo(actual.getRevenuTaxeExtra201()))
            .satisfies(
                e ->
                    assertThat(e.getRevenuNetExtraGlobal202())
                        .as("check revenuNetExtraGlobal202")
                        .isEqualTo(actual.getRevenuNetExtraGlobal202())
            )
            .satisfies(
                e ->
                    assertThat(e.getRevenuTaxeExtraGlobal203())
                        .as("check revenuTaxeExtraGlobal203")
                        .isEqualTo(actual.getRevenuTaxeExtraGlobal203())
            )
            .satisfies(e -> assertThat(e.getRevenuNetTotal204()).as("check revenuNetTotal204").isEqualTo(actual.getRevenuNetTotal204()))
            .satisfies(e -> assertThat(e.getRevenuTaxeTotal205()).as("check revenuTaxeTotal205").isEqualTo(actual.getRevenuTaxeTotal205()))
            .satisfies(
                e ->
                    assertThat(e.getRevenuNetTotalGlobal206())
                        .as("check revenuNetTotalGlobal206")
                        .isEqualTo(actual.getRevenuNetTotalGlobal206())
            )
            .satisfies(
                e ->
                    assertThat(e.getRevenuTaxeTotalGlobal207())
                        .as("check revenuTaxeTotalGlobal207")
                        .isEqualTo(actual.getRevenuTaxeTotalGlobal207())
            )
            .satisfies(
                e -> assertThat(e.getProdRevenuChambre208()).as("check prodRevenuChambre208").isEqualTo(actual.getProdRevenuChambre208())
            )
            .satisfies(e -> assertThat(e.getProdRevenuBq209()).as("check prodRevenuBq209").isEqualTo(actual.getProdRevenuBq209()))
            .satisfies(e -> assertThat(e.getProdRevenuExtra210()).as("check prodRevenuExtra210").isEqualTo(actual.getProdRevenuExtra210()))
            .satisfies(e -> assertThat(e.getProdRevenuTotal211()).as("check prodRevenuTotal211").isEqualTo(actual.getProdRevenuTotal211()))
            .satisfies(
                e ->
                    assertThat(e.getProdChambreNbNuitees212())
                        .as("check prodChambreNbNuitees212")
                        .isEqualTo(actual.getProdChambreNbNuitees212())
            )
            .satisfies(e -> assertThat(e.getTechCreateDate213()).as("check techCreateDate213").isEqualTo(actual.getTechCreateDate213()))
            .satisfies(e -> assertThat(e.getTechUpdateDate214()).as("check techUpdateDate214").isEqualTo(actual.getTechUpdateDate214()))
            .satisfies(e -> assertThat(e.getNumLigne215()).as("check numLigne215").isEqualTo(actual.getNumLigne215()))
            .satisfies(e -> assertThat(e.getResort216()).as("check resort216").isEqualTo(actual.getResort216()))
            .satisfies(e -> assertThat(e.getResvNameId217()).as("check resvNameId217").isEqualTo(actual.getResvNameId217()))
            .satisfies(e -> assertThat(e.getClientOId218()).as("check clientOId218").isEqualTo(actual.getClientOId218()))
            .satisfies(e -> assertThat(e.getTypeChb219()).as("check typeChb219").isEqualTo(actual.getTypeChb219()))
            .satisfies(e -> assertThat(e.getConfirmationNo220()).as("check confirmationNo220").isEqualTo(actual.getConfirmationNo220()))
            .satisfies(e -> assertThat(e.getClientMdmId221()).as("check clientMdmId221").isEqualTo(actual.getClientMdmId221()))
            .satisfies(e -> assertThat(e.getNameId222()).as("check nameId222").isEqualTo(actual.getNameId222()))
            .satisfies(
                e -> assertThat(e.getParentResvNameId223()).as("check parentResvNameId223").isEqualTo(actual.getParentResvNameId223())
            )
            .satisfies(e -> assertThat(e.getContactId224()).as("check contactId224").isEqualTo(actual.getContactId224()))
            .satisfies(e -> assertThat(e.getAgenceId225()).as("check agenceId225").isEqualTo(actual.getAgenceId225()))
            .satisfies(e -> assertThat(e.getAgenceNom226()).as("check agenceNom226").isEqualTo(actual.getAgenceNom226()))
            .satisfies(e -> assertThat(e.getSocieteId227()).as("check societeId227").isEqualTo(actual.getSocieteId227()))
            .satisfies(e -> assertThat(e.getGroupeId228()).as("check groupeId228").isEqualTo(actual.getGroupeId228()))
            .satisfies(e -> assertThat(e.getNumBloc229()).as("check numBloc229").isEqualTo(actual.getNumBloc229()))
            .satisfies(e -> assertThat(e.getTypeResv230()).as("check typeResv230").isEqualTo(actual.getTypeResv230()))
            .satisfies(e -> assertThat(e.getStatutResv231()).as("check statutResv231").isEqualTo(actual.getStatutResv231()))
            .satisfies(e -> assertThat(e.getDateDebutResv232()).as("check dateDebutResv232").isEqualTo(actual.getDateDebutResv232()))
            .satisfies(e -> assertThat(e.getDateFinResv233()).as("check dateFinResv233").isEqualTo(actual.getDateFinResv233()))
            .satisfies(
                e -> assertThat(e.getTruncDateDebutResv234()).as("check truncDateDebutResv234").isEqualTo(actual.getTruncDateDebutResv234())
            )
            .satisfies(
                e -> assertThat(e.getTruncDateFinResv235()).as("check truncDateFinResv235").isEqualTo(actual.getTruncDateFinResv235())
            )
            .satisfies(e -> assertThat(e.getDateAnnResv236()).as("check dateAnnResv236").isEqualTo(actual.getDateAnnResv236()))
            .satisfies(e -> assertThat(e.getPseudoRoomYn237()).as("check pseudoRoomYn237").isEqualTo(actual.getPseudoRoomYn237()))
            .satisfies(e -> assertThat(e.getCreateurResv238()).as("check createurResv238").isEqualTo(actual.getCreateurResv238()))
            .satisfies(e -> assertThat(e.getNomCreateurResv239()).as("check nomCreateurResv239").isEqualTo(actual.getNomCreateurResv239()))
            .satisfies(e -> assertThat(e.getCodeGarantie240()).as("check codeGarantie240").isEqualTo(actual.getCodeGarantie240()))
            .satisfies(e -> assertThat(e.getFlgDed241()).as("check flgDed241").isEqualTo(actual.getFlgDed241()))
            .satisfies(e -> assertThat(e.getCodePays242()).as("check codePays242").isEqualTo(actual.getCodePays242()))
            .satisfies(e -> assertThat(e.getLibPays243()).as("check libPays243").isEqualTo(actual.getLibPays243()))
            .satisfies(e -> assertThat(e.getCodeNationalite244()).as("check codeNationalite244").isEqualTo(actual.getCodeNationalite244()))
            .satisfies(e -> assertThat(e.getLibNationalite245()).as("check libNationalite245").isEqualTo(actual.getLibNationalite245()))
            .satisfies(e -> assertThat(e.getCodeSource246()).as("check codeSource246").isEqualTo(actual.getCodeSource246()))
            .satisfies(e -> assertThat(e.getLibSource247()).as("check libSource247").isEqualTo(actual.getLibSource247()))
            .satisfies(e -> assertThat(e.getCodeGrandSource248()).as("check codeGrandSource248").isEqualTo(actual.getCodeGrandSource248()))
            .satisfies(e -> assertThat(e.getCodeOrigine249()).as("check codeOrigine249").isEqualTo(actual.getCodeOrigine249()))
            .satisfies(e -> assertThat(e.getLibOrigine250()).as("check libOrigine250").isEqualTo(actual.getLibOrigine250()))
            .satisfies(e -> assertThat(e.getCodeMarche251()).as("check codeMarche251").isEqualTo(actual.getCodeMarche251()))
            .satisfies(e -> assertThat(e.getLibMarche252()).as("check libMarche252").isEqualTo(actual.getLibMarche252()))
            .satisfies(e -> assertThat(e.getCodeGrandMarche253()).as("check codeGrandMarche253").isEqualTo(actual.getCodeGrandMarche253()))
            .satisfies(e -> assertThat(e.getLibGrandMarche254()).as("check libGrandMarche254").isEqualTo(actual.getLibGrandMarche254()))
            .satisfies(e -> assertThat(e.getCodePrix255()).as("check codePrix255").isEqualTo(actual.getCodePrix255()))
            .satisfies(e -> assertThat(e.getCategPrix256()).as("check categPrix256").isEqualTo(actual.getCategPrix256()))
            .satisfies(e -> assertThat(e.getLibPrix257()).as("check libPrix257").isEqualTo(actual.getLibPrix257()))
            .satisfies(e -> assertThat(e.getNumChb258()).as("check numChb258").isEqualTo(actual.getNumChb258()))
            .satisfies(
                e -> assertThat(e.getDescriptionTypeChb259()).as("check descriptionTypeChb259").isEqualTo(actual.getDescriptionTypeChb259())
            )
            .satisfies(e -> assertThat(e.getCodeTypeChb260()).as("check codeTypeChb260").isEqualTo(actual.getCodeTypeChb260()))
            .satisfies(e -> assertThat(e.getClassChb261()).as("check classChb261").isEqualTo(actual.getClassChb261()))
            .satisfies(e -> assertThat(e.getCaractChb262()).as("check caractChb262").isEqualTo(actual.getCaractChb262()))
            .satisfies(
                e ->
                    assertThat(e.getTypeChbDeReservation263())
                        .as("check typeChbDeReservation263")
                        .isEqualTo(actual.getTypeChbDeReservation263())
            )
            .satisfies(
                e ->
                    assertThat(e.getDescriptionTypeChbDeResv264())
                        .as("check descriptionTypeChbDeResv264")
                        .isEqualTo(actual.getDescriptionTypeChbDeResv264())
            )
            .satisfies(
                e -> assertThat(e.getCodeTypeChbDeResv265()).as("check codeTypeChbDeResv265").isEqualTo(actual.getCodeTypeChbDeResv265())
            )
            .satisfies(
                e ->
                    assertThat(e.getStatutDeReservation266())
                        .as("check statutDeReservation266")
                        .isEqualTo(actual.getStatutDeReservation266())
            )
            .satisfies(
                e ->
                    assertThat(e.getCircuitDistribution267())
                        .as("check circuitDistribution267")
                        .isEqualTo(actual.getCircuitDistribution267())
            )
            .satisfies(
                e ->
                    assertThat(e.getCircuitDistribUserRegroup268())
                        .as("check circuitDistribUserRegroup268")
                        .isEqualTo(actual.getCircuitDistribUserRegroup268())
            )
            .satisfies(e -> assertThat(e.getNumCrs269()).as("check numCrs269").isEqualTo(actual.getNumCrs269()))
            .satisfies(e -> assertThat(e.getTypeRefCrs270()).as("check typeRefCrs270").isEqualTo(actual.getTypeRefCrs270()))
            .satisfies(e -> assertThat(e.getCrsInsertDate271()).as("check crsInsertDate271").isEqualTo(actual.getCrsInsertDate271()))
            .satisfies(e -> assertThat(e.getDateCreaResv272()).as("check dateCreaResv272").isEqualTo(actual.getDateCreaResv272()))
            .satisfies(e -> assertThat(e.getDatePremier273()).as("check datePremier273").isEqualTo(actual.getDatePremier273()))
            .satisfies(e -> assertThat(e.getStatutPremier274()).as("check statutPremier274").isEqualTo(actual.getStatutPremier274()))
            .satisfies(e -> assertThat(e.getDateDernier275()).as("check dateDernier275").isEqualTo(actual.getDateDernier275()))
            .satisfies(e -> assertThat(e.getStatutDernier276()).as("check statutDernier276").isEqualTo(actual.getStatutDernier276()))
            .satisfies(
                e -> assertThat(e.getDateDernierPseudo277()).as("check dateDernierPseudo277").isEqualTo(actual.getDateDernierPseudo277())
            )
            .satisfies(
                e ->
                    assertThat(e.getStatutDernierPseudo278())
                        .as("check statutDernierPseudo278")
                        .isEqualTo(actual.getStatutDernierPseudo278())
            )
            .satisfies(e -> assertThat(e.getDiffDtCreaAnn279()).as("check diffDtCreaAnn279").isEqualTo(actual.getDiffDtCreaAnn279()))
            .satisfies(e -> assertThat(e.getDiffDtArrAnn280()).as("check diffDtArrAnn280").isEqualTo(actual.getDiffDtArrAnn280()))
            .satisfies(e -> assertThat(e.getLeadtime281()).as("check leadtime281").isEqualTo(actual.getLeadtime281()))
            .satisfies(e -> assertThat(e.getLos282()).as("check los282").isEqualTo(actual.getLos282()))
            .satisfies(e -> assertThat(e.getOccupantsGroupe283()).as("check occupantsGroupe283").isEqualTo(actual.getOccupantsGroupe283()))
            .satisfies(e -> assertThat(e.getNbNuitee284()).as("check nbNuitee284").isEqualTo(actual.getNbNuitee284()))
            .satisfies(e -> assertThat(e.getNbNuiteeNnDed285()).as("check nbNuiteeNnDed285").isEqualTo(actual.getNbNuiteeNnDed285()))
            .satisfies(e -> assertThat(e.getNbResvAnn286()).as("check nbResvAnn286").isEqualTo(actual.getNbResvAnn286()))
            .satisfies(e -> assertThat(e.getNbAdu287()).as("check nbAdu287").isEqualTo(actual.getNbAdu287()))
            .satisfies(e -> assertThat(e.getNbEnf288()).as("check nbEnf288").isEqualTo(actual.getNbEnf288()))
            .satisfies(e -> assertThat(e.getNbPersDayU289()).as("check nbPersDayU289").isEqualTo(actual.getNbPersDayU289()))
            .satisfies(e -> assertThat(e.getNbPersArr290()).as("check nbPersArr290").isEqualTo(actual.getNbPersArr290()))
            .satisfies(e -> assertThat(e.getNbPersDep291()).as("check nbPersDep291").isEqualTo(actual.getNbPersDep291()))
            .satisfies(e -> assertThat(e.getNbPersAnn292()).as("check nbPersAnn292").isEqualTo(actual.getNbPersAnn292()))
            .satisfies(e -> assertThat(e.getNbPersNoshow293()).as("check nbPersNoshow293").isEqualTo(actual.getNbPersNoshow293()))
            .satisfies(e -> assertThat(e.getNbChbDayU294()).as("check nbChbDayU294").isEqualTo(actual.getNbChbDayU294()))
            .satisfies(e -> assertThat(e.getNbChbArr295()).as("check nbChbArr295").isEqualTo(actual.getNbChbArr295()))
            .satisfies(e -> assertThat(e.getNbChbDep296()).as("check nbChbDep296").isEqualTo(actual.getNbChbDep296()))
            .satisfies(e -> assertThat(e.getNbChbAnn297()).as("check nbChbAnn297").isEqualTo(actual.getNbChbAnn297()))
            .satisfies(e -> assertThat(e.getNbChbNoshow298()).as("check nbChbNoshow298").isEqualTo(actual.getNbChbNoshow298()))
            .satisfies(
                e -> assertThat(e.getRevenuNetChambre299()).as("check revenuNetChambre299").isEqualTo(actual.getRevenuNetChambre299())
            )
            .satisfies(
                e -> assertThat(e.getRevenuTaxeChambre300()).as("check revenuTaxeChambre300").isEqualTo(actual.getRevenuTaxeChambre300())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDmOResvUpdatableRelationshipsEquals(DmOResv expected, DmOResv actual) {}
}
